import { motion } from "framer-motion";
import {
    Building2, Users, ShieldCheck, GraduationCap,
    BarChart3, FileCheck, Info, TrendingUp, LogOut, Download, FileText
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import AppHeader from "@/components/AppHeader";
import DashboardCard from "@/components/DashboardCard";
import BottomNav from "@/components/BottomNav";
import SOSAlert from "@/components/SOSAlert";
import { useAuth } from "@/context/AuthContext";
import { useComplaints } from "@/context/ComplaintContext";
import { toast } from "sonner";

const InstitutionDashboard = () => {
    const navigate = useNavigate();
    const { user, logout } = useAuth();
    const { complaints } = useComplaints();
    const institution = user?.institution || localStorage.getItem("user_institution") || "Delhi University";

    const handleLogout = () => {
        logout();
        navigate("/role-selection");
    };

    const stats = {
        resolved: complaints.filter(c => c.status === "closed").length,
        review: complaints.filter(c => c.status === "under_review" || c.status === "verified").length,
        escalated: complaints.filter(c => c.priority === "emergency" && c.status !== "closed").length,
    };

    const handleDownloadReport = () => {
        let reportContent = `SafeVoice Institutional POSH Compliance Report\nInstitution: ${institution}\nDate Generated: ${new Date().toLocaleDateString()}\n\n`;

        // Add Summary Stats
        reportContent += `Status,Count\nResolved Successfully,${stats.resolved}\nUnder IC Review,${stats.review}\nEscalated / Emergency,${stats.escalated}\n\n`;
        reportContent += `Total Active/Reviewed Cases,${stats.review + stats.escalated}\n\n`;

        // Add Detailed Cases
        reportContent += `\n--- DETAILED CASE LOG ---\n\n`;
        reportContent += `Case ID,Date Submitted,Complaint Type,Priority Level,Current Status\n`;

        complaints.forEach(c => {
            const date = c.created_at || c.createdAt ? new Date(c.created_at || c.createdAt).toLocaleDateString() : 'Unknown Data';
            // Escape commas in type just in case
            const safeType = `"${c.type || 'Unknown'}"`;
            reportContent += `${c.caseId || c._id},${date},${safeType},${c.priority || 'medium'},${c.status || 'pending'}\n`;
        });

        reportContent += `\n* Generated by SafeVoice System for Compliance Submission`;

        const blob = new Blob([reportContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', `${institution.replace(/\s+/g, '_')}_POSH_Report_2025_26.csv`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        toast.success("Annual Report downloaded successfully");
    };

    const handleDownloadSingleCase = (c: any) => {
        // Handle potential nested complaintRef objects from the backend
        const actualCase = c.complaintRef || c;

        // Sometimes actualCase is just the string ID of the complaint
        const reportId = typeof actualCase === 'string'
            ? actualCase
            : (actualCase._id || actualCase.caseId || actualCase.complaintId || c._id);

        // Fallback clean check if it starts with new_ 
        let cleanId = reportId?.startsWith('new_') ? reportId.replace('new_', '') : reportId;

        // 🔥 Prevent literal "undefined" string from being used as a valid ID
        if (String(cleanId).trim() === "undefined" || String(cleanId).trim() === "null") {
            cleanId = c._id?.startsWith('new_') ? c._id.replace('new_', '') : c._id;
        }

        if (cleanId) {
            navigate(`/report/${cleanId}`);
        } else {
            toast.error("Invalid case document format.");
        }
    };

    return (
        <div className="flex min-h-screen flex-col bg-background pb-20">
            <SOSAlert institution={institution} />
            <div className="gradient-primary px-4 pb-6 pt-8">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <Building2 className="h-6 w-6 text-primary-foreground" />
                        <div>
                            <h1 className="font-display text-lg font-bold text-primary-foreground">Institution Portal</h1>
                            <p className="text-xs text-primary-foreground/60">{institution}</p>
                        </div>
                    </div>
                    <button
                        onClick={handleLogout}
                        className="rounded-full bg-primary-foreground/10 p-2 text-primary-foreground hover:bg-primary-foreground/20 transition-colors"
                    >
                        <LogOut className="h-4 w-4" />
                    </button>
                </div>

                {/* High Level Stats */}
                <div className="mt-6 grid grid-cols-2 gap-3">
                    <div className="rounded-xl bg-primary-foreground/10 p-4 backdrop-blur-md">
                        <div className="flex items-center gap-2 text-primary-foreground/60">
                            <ShieldCheck className="h-4 w-4" />
                            <span className="text-[10px] uppercase font-semibold tracking-wider">Compliance Score</span>
                        </div>
                        <p className="mt-1 font-display text-2xl font-bold text-primary-foreground">92%</p>
                        <div className="mt-2 h-1 w-full bg-primary-foreground/20 rounded-full overflow-hidden">
                            <div className="h-full bg-safety w-[92%]" />
                        </div>
                    </div>
                    <div className="rounded-xl bg-primary-foreground/10 p-4 backdrop-blur-md">
                        <div className="flex items-center gap-2 text-primary-foreground/60">
                            <Users className="h-4 w-4" />
                            <span className="text-[10px] uppercase font-semibold tracking-wider">Staff Trained</span>
                        </div>
                        <p className="mt-1 font-display text-2xl font-bold text-primary-foreground">845</p>
                        <p className="text-[10px] text-safety font-medium leading-none mt-1">✓ 88% complete</p>
                    </div>
                </div>
            </div>

            <div className="flex-1 px-4 py-6">
                {/* Compliance Alert */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="mb-6 rounded-xl border border-safety/30 bg-safety/5 p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
                >
                    <div className="flex items-start gap-3">
                        <div className="mt-0.5 rounded-full bg-safety/20 p-1.5 shrink-0">
                            <ShieldCheck className="h-4 w-4 text-safety" />
                        </div>
                        <div>
                            <h4 className="font-display text-sm font-bold text-foreground">Annual Report Ready</h4>
                            <p className="mt-1 text-xs text-muted-foreground">Your 2025-26 POSH Annual Compliance Report has been generated and is ready for submission.</p>
                        </div>
                    </div>
                    <button
                        onClick={handleDownloadReport}
                        className="shrink-0 flex items-center gap-2 bg-safety text-white px-4 py-2 rounded-lg text-xs font-bold hover:bg-safety/90 transition-colors"
                    >
                        <Download className="h-4 w-4" /> Download
                    </button>
                </motion.div>

                {/* Administration Links */}
                <h3 className="mb-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider">Organizational Control</h3>
                <div className="grid grid-cols-2 gap-3">
                    <DashboardCard
                        icon={GraduationCap}
                        title="Training Portal"
                        description="Manage mandatory staff POSH sessions"
                        variant="shield"
                        onClick={() => navigate("/institution-training")}
                    />
                    <DashboardCard
                        icon={BarChart3}
                        title="Analytics"
                        description="Institutional sentiment & trends"
                        onClick={() => navigate("/institution-analytics")}
                    />
                    <DashboardCard
                        icon={FileCheck}
                        title="IC Committee"
                        description="Manage Internal Committee members"
                        onClick={() => navigate("/institution-ic")}
                    />
                    <DashboardCard
                        icon={TrendingUp}
                        title="Transparency"
                        description="View your public safety score"
                        variant="safety"
                        onClick={() => navigate("/institution-transparency")}
                    />
                </div>

                {/* Information Grid */}
                <div className="mt-8 space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Case Overview (Aggregated)</h3>
                        <button className="text-[10px] text-primary font-bold uppercase hover:underline">Full Details</button>
                    </div>
                    <div className="rounded-xl border border-border bg-card p-4">
                        <div className="flex items-center justify-between border-b border-border pb-3 mb-3">
                            <div className="flex items-center gap-2">
                                <div className="h-2 w-2 rounded-full bg-safety" />
                                <span className="text-xs font-medium text-foreground">Resolved Successfully</span>
                            </div>
                            <span className="text-xs font-bold text-foreground">{stats.resolved}</span>
                        </div>
                        <div className="flex items-center justify-between border-b border-border pb-3 mb-3">
                            <div className="flex items-center gap-2">
                                <div className="h-2 w-2 rounded-full bg-warning" />
                                <span className="text-xs font-medium text-foreground">Under IC Review</span>
                            </div>
                            <span className="text-xs font-bold text-foreground">{stats.review}</span>
                        </div>
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <div className="h-2 w-2 rounded-full bg-emergency" />
                                <span className="text-xs font-medium text-foreground">Escalated / Emergency</span>
                            </div>
                            <span className="text-xs font-bold text-foreground">{stats.escalated}</span>
                        </div>
                    </div>

                    <div className="rounded-xl bg-muted/50 p-4 flex gap-3">
                        <Info className="h-5 w-5 text-muted-foreground shrink-0" />
                        <p className="text-[10px] text-muted-foreground leading-relaxed italic">
                            Per POSH Act Section 16, individual victim and respondent identities are not visible in the Institutional Dashboard. Only the Internal Committee has access to specific case details.
                        </p>
                    </div>
                </div>

                {/* Individual Case Reports Section */}
                <div className="mt-8 space-y-4">
                    <div className="flex items-center justify-between">
                        <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Individual Case Reports</h3>
                    </div>
                    {complaints.length > 0 ? (
                        <div className="grid gap-3">
                            {complaints.map((c: any) => (
                                <div id={`inst-case-card-${c.caseId || c._id}`} key={c._id || c.caseId} className="flex items-center justify-between rounded-xl border border-border bg-card p-4 hover:border-primary/30 transition-colors">
                                    <div className="flex items-start gap-3">
                                        <div className="rounded-full justify-center items-center flex bg-primary/10 h-8 w-8 shrink-0">
                                            <FileText className="h-4 w-4 text-primary" />
                                        </div>
                                        <div>
                                            <h4 className="font-display text-sm font-bold text-foreground">{c.caseId || c._id}</h4>
                                            <div className="flex gap-2 items-center mt-1">
                                                <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider 
                                                    ${c.priority === 'emergency' ? 'bg-emergency/10 text-emergency' :
                                                        c.priority === 'high' ? 'bg-safety/10 text-safety' :
                                                            c.priority === 'low' ? 'bg-success/10 text-success' :
                                                                'bg-warning/10 text-warning'}`}>
                                                    {c.priority || 'medium'}
                                                </span>
                                                <span className="text-xs text-muted-foreground">
                                                    {c.created_at || c.createdAt ? new Date(c.created_at || c.createdAt).toLocaleDateString() : 'Unknown Date'}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => handleDownloadSingleCase(c)}
                                        className="rounded-lg bg-secondary/50 p-2 text-foreground hover:bg-secondary transition-colors"
                                        title="Download Case Report"
                                    >
                                        <Download className="h-4 w-4" />
                                    </button>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="rounded-xl border border-dashed border-border p-8 text-center text-muted-foreground">
                            <p className="text-sm">No cases reported yet.</p>
                        </div>
                    )}
                </div>
                {/* Spacer to Ensure Bottom Nav Doesn't Cover Content */}
                <div className="h-20" />
            </div>

            <BottomNav />
        </div>
    );
};

export default InstitutionDashboard;
